### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mandarvaze** [claytron/ever2simple#20]
installed fine using pip - but when executed ran into following error :

	$ ever2simple
	Traceback (most recent call last):
	  File "/usr/local/bin/ever2simple", line 7, in <module>
	    from ever2simple.core import main
	  File "/usr/local/lib/python3.5/site-packages/ever2simple/core.py", line 18
	    print 'File does not exist: %s' % filepath
	                                  ^
	SyntaxError: Missing parentheses in call to 'print'

**Comment by smsheth** [comment]
I'm getting the same error. I tried running in it in virtualenv and couldn't get it to run either. I'm pretty new to all of this so I'm not really sure exactly what I'm doing beyond just following the instructions.
Please help.

**Comment by mandarvaze** [comment]
@smsheth I think your only option is to use python 2
Without knowing more details about your setup, it is difficult to help you further (in case you don't know how to set up python2)

**Comment by jlbrewer** [comment]
Disclaimer: I've taken courses in Python but I'm not a coder.

Working from @dougdiego 's fork [I started working through the stacktraces](https://github.com/jlbrewer/ever2simple/tree/python3x) to make this work in my Python 3 setup. The current commit is as far as I've gotten before running into issue #21.

**Comment by joshbmartin** [comment]
This seems to still be an issue.

**Comment by mandarvaze** [comment]
@joshbmartin **This** one seems to be abandoned/not updated in 3 years. So if you installed using `pip` - you are sure to face the issue.

Others (@jlbrewer and @dougdiego) seem to be maintaining their separate forks, which are much more up to date. @jlbrewer also seems to have python3x branch.

So you consider using code from either of these repos, and see if python3 support works.
