### ISSUE TITLE
Cannot find file

### ISSUE THREAD

**Issue by webbexpert** [claytron/ever2simple#22]
Hi! 
I was able to install your app and run it, however, it seems to not accept any arguments to the file or filepath the the enex file. I've attempted relative paths, and full qualified paths, with and without quoted identifiers... no luck
Any ideas on why this is failing? Thanks in advance!
Command:
C:\Users\Username\Desktop\Python>ever2simple DeveloperOuttake.enex
Output:
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\ever2simple.exe\__main__.py", line 5, in <module>
  File "c:\program files\python37\lib\site-packages\ever2simple\core.py", line 18
    print 'File does not exist: %s' % filepath
                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('File does not exist: %s' % filepath)?

**Comment by webbexpert** [comment]
Interesting .. getting this error even without any parameters supplied. Thoughts? Let me know!!

**Comment by elinsky** [comment]
I get the same error.  Even when I run the command
`ever2simple -h`

I've tried uninstalling and reinstalling the tool and still get the error.
