### ISSUE TITLE
ImportError while running.

### ISSUE THREAD

**Issue by iMerica** [claytron/ever2simple#4]
Just installed successfully and got this error while running the app

```
❯ ever2simple notes.enex > simplenote.json
Traceback (most recent call last):
  File "/usr/local/bin/ever2simple", line 9, in <module>
    load_entry_point('ever2simple==1.1', 'console_scripts', 'ever2simple')()
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
  File "build/bdist.macosx-10.10-x86_64/egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/usr/local/lib/python2.7/site-packages/ever2simple/core.py", line 3, in <module>
    from ever2simple.converter import EverConverter
  File "/usr/local/lib/python2.7/site-packages/ever2simple/converter.py", line 8, in <module>
    from lxml import etree
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/lxml/etree.so, 2): Symbol not found: _lzma_auto_decoder
  Referenced from: /usr/local/lib/python2.7/site-packages/lxml/etree.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/lxml/etree.so
```

**Comment by claytron** [comment]
Appears to be an issue with the lxml installation. Quick search brought this up:

http://stackoverflow.com/a/25140836/34530

I've not tested with Python 3 much. You might try using the latest Python 2 if you can't get lxml to work in Python 3.
